; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
include_dir=uCNC
src_dir=uCNC
default_envs = LPC176X-SKR-v1_4-TURBO
extra_configs = 
  uCNC/src/hal/boards/avr/avr.ini
  uCNC/src/hal/boards/samd21/samd21.ini
  uCNC/src/hal/boards/stm32/stm32.ini
  uCNC/src/hal/boards/esp8266/esp8266.ini
  uCNC/src/hal/boards/lpc176x/lpc176x.ini
  uCNC/src/hal/boards/esp32/esp32.ini
  uCNC/src/hal/boards/rp2040/rp2040.ini
	uCNC/src/hal/boards/rp2350/rp2350.ini
  uCNC/src/hal/mcus/virtual/virtual.ini

[env]
framework = arduino
monitor_speed = 115200
monitor_eol = LF
monitor_echo = yes
monitor_filters = colorize, time
extra_scripts =
	pre:ucnc_modules.py
;µCNC web builder generated config
build_flags =
  -DENABLE_DEBUG_STREAM
; -DDISABLE_MULTISTREAM_SERIAL
  -DDETACH_UART_FROM_MAIN_PROTOCOL
  ; -DDEBUG_STREAM="(&usb_grbl_stream)"
  -DENABLE_MODBUS_VERBOSE

custom_ucnc_modules_url = https://github.com/Paciente8159/uCNC-modules/archive/refs/heads/master.zip
custom_ucnc_modules = m17_m18, m42, m62_m65, m67_m68, sd_card_v2, tmc_driver
lib_deps =
board =

upload_port = /Volumes/BIGCNC
upload_protocol = cmsis-dap
; upload_command = /Users/matt/pyocd-venv/bin/pyocd flash --target lpc1768 -a 0x4000 $SOURCE
upload_flags = 
  --base-address 
  0x4000
; upload_port = localhost:5555
; debug_tool = cmsis-dap
; debug_port = :5555
; debug_server = 
;   /Users/matt/pyocd-venv/bin/pyocd
;   gdbserver
;   -t
;   lpc1768
; debug_server = tool-pyocd

; debug_init_cmds = 
;   define pio_reset_halt_target
;       interrupt
;       monitor reset
;       monitor halt
;   end
;   define pio_reset_run_target
;       monitor reset
;       monitor go
;   end
;   target extended-remote $DEBUG_PORT
;   pio_reset_halt_target
;   $LOAD_CMDS
;   $INIT_BREAK
debug_init_break = break cnc_init
; debug_load_cmds = load 0x4000