#ifndef CNC_HAL_OVERRIDES_H
#define CNC_HAL_OVERRIDES_H
#ifdef __cplusplus
extern "C"
{
#endif

#include "cnc_hal_reset.h"
#define ENABLE_COOLANT
#define S_CURVE_ACCELERATION_LEVEL -1
#define ENABLE_EXTRA_SYSTEM_CMDS
#define ENABLE_RS274NGC_EXPRESSIONS
#define DISABLE_ALL_CONTROLS
#define PROBE_PULLUP_ENABLE
#define TOOL1 vfd_modbus
#define VFD_TX_PIN DOUT27
#define VFD_RX_PIN DIN27
#define VFD_BAUDRATE 38400
#define VFD_COOLANT_FLOOD DOUT1
#define VFD_COOLANT_MIST DOUT2
#define SOFT_SPI_ENABLED
#define SOFT_SPI_CLK DOUT30
#define SOFT_SPI_SDO DOUT29
#define SOFT_SPI_SDI DIN29
#define IC74HC595_COUNT 0
#define ENCODERS 0
#define ENABLE_MAIN_LOOP_MODULES
#define ENABLE_PARSER_MODULES
#define SD_CARD_INTERFACE SD_CARD_HW_SPI2
#define SD_SPI_CS SPI2_CS
#define SD_CARD_DETECT_PIN DIN19
#define FF_USE_LFN 1
#define STEPPER0_HAS_TMC
#define STEPPER0_DRIVER_TYPE 2209
#define STEPPER0_TMC_INTERFACE TMC_UART
#define STEPPER0_UART_TX DOUT20
#define STEPPER0_UART_RX DIN20
#define STEPPER0_UART_ADDRESS 0
#define STEPPER0_CURRENT_MA 801
#define STEPPER0_MICROSTEP 4
#define STEPPER0_RSENSE 0.11
#define STEPPER0_HOLD_MULT 0.7
#define STEPPER0_STEALTHCHOP_THERSHOLD 0
#define STEPPER0_ENABLE_INTERPLATION true
#define STEPPER1_HAS_TMC
#define STEPPER1_DRIVER_TYPE 2209
#define STEPPER1_TMC_INTERFACE TMC_UART
#define STEPPER1_UART_TX DOUT21
#define STEPPER1_UART_RX DIN21
#define STEPPER1_UART_ADDRESS 0
#define STEPPER1_CURRENT_MA 801
#define STEPPER1_MICROSTEP 4
#define STEPPER1_RSENSE 0.11
#define STEPPER1_HOLD_MULT 0.7
#define STEPPER1_STEALTHCHOP_THERSHOLD 0
#define STEPPER1_ENABLE_INTERPLATION true
#define STEPPER2_HAS_TMC
#define STEPPER2_DRIVER_TYPE 2209
#define STEPPER2_TMC_INTERFACE TMC_UART
#define STEPPER2_UART_TX DOUT22
#define STEPPER2_UART_RX DIN22
#define STEPPER2_UART_ADDRESS 0
#define STEPPER2_CURRENT_MA 801
#define STEPPER2_MICROSTEP 4
#define STEPPER2_RSENSE 0.11
#define STEPPER2_HOLD_MULT 0.7
#define STEPPER2_STEALTHCHOP_THERSHOLD 0
#define STEPPER2_ENABLE_INTERPLATION true
#define STEPPER3_HAS_TMC
#define STEPPER3_DRIVER_TYPE 2209
#define STEPPER3_TMC_INTERFACE TMC_UART
#define STEPPER3_UART_TX DOUT23
#define STEPPER3_UART_RX DIN23
#define STEPPER3_UART_ADDRESS 0
#define STEPPER3_CURRENT_MA 900
#define STEPPER3_MICROSTEP 4
#define STEPPER3_RSENSE 0.11
#define STEPPER3_HOLD_MULT 0.7
#define STEPPER3_STEALTHCHOP_THERSHOLD 0
#define STEPPER3_ENABLE_INTERPLATION true
#define STEPPER4_HAS_TMC
#define STEPPER4_DRIVER_TYPE 2209
#define STEPPER4_TMC_INTERFACE TMC_UART
#define STEPPER4_UART_TX DOUT24
#define STEPPER4_UART_RX DIN24
#define STEPPER4_UART_ADDRESS 0
#define STEPPER4_CURRENT_MA 801
#define STEPPER4_MICROSTEP 4
#define STEPPER4_RSENSE 0.11
#define STEPPER4_HOLD_MULT 0.7
#define STEPPER4_STEALTHCHOP_THERSHOLD 0
#define STEPPER4_ENABLE_INTERPLATION true
//Custom configurations
// #undef STEPPER0_DRIVER_TYPE
// #define STEPPER0_DRIVER_TYPE 5160
// #define STEPPER0_GLOBALSCALER 256

#define PROBE2 DIN32
// #define PROBE2_INVERT

#define LOAD_MODULES_OVERRIDE() ({LOAD_MODULE(m17_m18);LOAD_MODULE(m42);LOAD_MODULE(m62_m65);LOAD_MODULE(m67_m68);LOAD_MODULE(sd_card_v2);LOAD_MODULE(tmc_driver);})

#ifdef __cplusplus
}
#endif
#endif
